#!/usr/bin/env python3
"""Embed the selected, frozen enemy checkpoint in the browser build."""
import hashlib
import json
import math
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from training.selfplay import ENEMY

CHECKPOINT = ROOT / 'training/results/recurrent-v4-hour2/frozen.json'
OUTPUT = ROOT / 'src/p_worthy_champion.h'


def render():
    data = CHECKPOINT.read_bytes()
    policy = json.loads(data)['policies']['enemy']
    params, weights = policy['params'], policy['network']
    if len(params) != len(ENEMY) or any(type(v) is not int or not lo <= v <= hi
            for v, (_, lo, hi, _) in zip(params, ENEMY)):
        raise ValueError('Champion parameters do not match the allowed enemy schema')
    if weights is None or len(weights) != 1650 or any(not math.isfinite(v) or abs(v) > 4 for v in weights):
        raise ValueError('Champion must contain 1650 bounded, finite neural weights')
    def literal(v):
        text = format(v, '.9g')  # Same decimal precision as the native arena protocol.
        if '.' not in text and 'e' not in text: text += '.0'
        return text + 'f'
    fields = '\n'.join(f'    .{row[0]} = {value},' for value, row in zip(params, ENEMY))
    rows = '\n'.join('    ' + ', '.join(literal(v) for v in weights[i:i+8]) + ','
                     for i in range(0, len(weights), 8))
    return f'''// Generated by scripts/export_worthy_policy.py. GPL-2.0-or-later.
// Source: training/results/recurrent-v4-hour2/frozen.json (enemy only).
// Checkpoint SHA-256: {hashlib.sha256(data).hexdigest()}
#ifndef P_WORTHY_CHAMPION_H
#define P_WORTHY_CHAMPION_H
#include <stddef.h>
#include "p_worthy.h"
#include "p_policy_net.h"
static const worthy_policy_t worthy_champion_policy = {{
{fields}
}};
static const float worthy_champion_weights[TACTIC_WEIGHTS] = {{
{rows}
}};

// Browser opt-in only: offline training's reference controllers stay unchanged.
static void Worthy_UseChampion(int enabled)
{{
    P_WorthySetPolicy(enabled ? &worthy_champion_policy : NULL);
    P_WorthySetRecurrentNetwork(enabled ? worthy_champion_weights : NULL);
    P_WorthySetDeterministicFire(enabled);
    P_WorthyResetNavigation();
    P_WorthySetEnabled(enabled);
}}
#endif
'''


if __name__ == '__main__':
    content = render()
    if '--check' in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit('Embedded champion is stale; run scripts/export_worthy_policy.py')
    else:
        OUTPUT.write_text(content)
